// ====== Candle Quest Academy — story, lessons & quizzes ======
// Characters: Sensei Hoshi (wise owl mentor), Kitsu (fox mascot), Kazuo (friendly rival)

const SENSEI = { name: "Sensei Hoshi", emoji: "🦉" };
const KITSU  = { name: "Kitsu the Fox", emoji: "🦊" };
const KAZUO  = { name: "Rival Kazuo", emoji: "😎" };

const RANKS = [
  { xp: 0,   name: "Academy Rookie",        emoji: "🐣" },
  { xp: 80,  name: "Candle Cadet",          emoji: "🕯️" },
  { xp: 200, name: "Chart Ninja",           emoji: "🥷" },
  { xp: 350, name: "Risk Guardian",         emoji: "🛡️" },
  { xp: 520, name: "Market Samurai",        emoji: "⚔️" },
  { xp: 700, name: "Legendary Trade Master", emoji: "🐉" },
];

const AVATARS = ["🦊", "🐱", "🐲", "🥷", "⚡", "🌸", "🤖", "🐼"];

const ARCS = [
  {
    id: "arc1",
    emoji: "⛩️",
    name: "Arc 1: Welcome to the Dojo",
    desc: "What is a market? What is a futures contract?",
    lessons: [
      { c: SENSEI, t: "Welcome, young trader! I am <strong>Sensei Hoshi</strong>, master of this dojo. You wish to learn the ancient art of <em>trading</em>? Then listen well!" },
      { c: SENSEI, t: "A <strong>market</strong> is simply a place where people <em>buy</em> and <em>sell</em> things. A school card-trading club is a market! Some kids want to buy a rare card, some want to sell one." },
      { c: KITSU,  t: "And here's the secret, kya~! Prices move because of <strong>buyers and sellers</strong>. If LOTS of kids want the rare dragon card, its price goes <em>UP</em>! If everyone wants to sell it... price goes <em>DOWN</em>!" },
      { c: SENSEI, t: "Now, the special scroll of this dojo: the <strong>futures contract</strong>. It is a <em>promise</em> to buy or sell something at a set price on a future day." },
      { c: SENSEI, t: "Imagine you tell your friend: <em>'Next Friday, I promise to trade you my dragon card for 10 Koins — no matter what!'</em> That promise itself becomes valuable. If the dragon card becomes super popular by Thursday, your friend's promise to get it for only 10 Koins is a treasure!" },
      { c: KAZUO,  t: "Heh. And real traders don't even wait until Friday. They buy and sell the <strong>promises themselves</strong>, all day long. Corn, gold, oil, stock indexes — there are futures for all of them." },
      { c: SENSEI, t: "We will train as <strong>intraday traders</strong> — also called <em>day traders</em>. Our rule: every trade opens and closes on the <strong>same day</strong>. Like a ninja mission that must finish before sunset! 🌅" },
      { c: SENSEI, t: "One more thing, and it is the most important scroll of all: in this dojo we use pretend <strong>Koins</strong>. Real futures trading is <em>very risky</em> and only for trained adults. Master the art here first. Now — to your first quiz!" },
    ],
    quiz: [
      { q: "What is a market?",
        o: ["A place where people buy and sell things", "A type of video game", "A kind of candlestick", "A ninja weapon"],
        a: 0, e: "Yes! A market is anywhere buyers and sellers meet — even a card-trading club at school." },
      { q: "A futures contract is...",
        o: ["A magic spell", "A promise to buy or sell something at a set price on a future day", "A kind of money", "A chart pattern"],
        a: 1, e: "Exactly! It's a promise about a future trade — and traders trade the promises themselves." },
      { q: "If LOTS of people suddenly want to buy something, what usually happens to its price?",
        o: ["It goes down", "It disappears", "It goes up", "Nothing ever changes"],
        a: 2, e: "More buyers than sellers pushes the price UP. That's the heartbeat of every market!" },
      { q: "What is the day trader's golden rule in our dojo?",
        o: ["Hold trades for years", "Open and close every trade on the same day", "Only trade on weekends", "Never close a trade"],
        a: 1, e: "Right! Intraday means in-the-day. The mission ends before the market closes — like a ninja home before sunset." },
    ],
  },
  {
    id: "arc2",
    emoji: "🕯️",
    name: "Arc 2: The Language of Candles",
    desc: "Read candlestick charts like a ninja reads scrolls.",
    lessons: [
      { c: SENSEI, t: "To trade, you must read the market's secret language: the <strong>candlestick chart</strong>. Each candle tells the story of the price during a short time — like one panel in a manga!" },
      { c: SENSEI, t: "A candle has a thick <strong>body</strong> and thin <strong>wicks</strong> on top and bottom. The body shows where the price <em>opened</em> and where it <em>closed</em>." },
      { c: KITSU,  t: "Color code, kya~! A <strong>green candle</strong> means the price went <em>UP</em> during that time — the heroes won that battle! A <strong>red candle</strong> means the price went <em>DOWN</em> — the bears won. 🐻" },
      { c: SENSEI, t: "The <strong>wicks</strong> are the shadows of the battle. The top wick shows the <em>highest</em> price reached; the bottom wick shows the <em>lowest</em>. A long wick means the price tried to go there... but got pushed back!" },
      { c: KAZUO,  t: "Pro tip: one candle is one panel, but the <strong>whole chart is the story</strong>. Lots of big green candles in a row? Buyers are powerful today. Lots of red? Sellers rule." },
      { c: SENSEI, t: "In our dojo's chart, each candle is a few minutes of the trading day. Watch them form, one by one, and you will feel the market's rhythm. Quiz time, then your <strong>first dojo mission</strong> awaits!" },
    ],
    quiz: [
      { q: "What does a GREEN candle mean?",
        o: ["The price went down", "The market is closed", "The price went up during that time", "A trade was cancelled"],
        a: 2, e: "Green = up! The price closed higher than it opened." },
      { q: "What do the thin wicks on a candle show?",
        o: ["The highest and lowest prices reached", "How many traders were online", "The candle's age", "Nothing important"],
        a: 0, e: "Wicks are the shadows of the battle — the extremes the price touched before getting pushed back." },
      { q: "You see many big RED candles in a row. Who is winning right now?",
        o: ["The buyers", "The sellers", "Nobody", "The referees"],
        a: 1, e: "Sellers (the bears 🐻) are in control — the price keeps closing lower." },
      { q: "The thick part of the candle is called the...",
        o: ["Wick", "Shadow", "Body", "Handle"],
        a: 2, e: "The body shows where price opened and closed. The wicks are the thin lines." },
    ],
  },
  {
    id: "arc3",
    emoji: "🌊",
    name: "Arc 3: Riding the Trend Wave",
    desc: "Trends, support & resistance — surf with the market, not against it.",
    lessons: [
      { c: SENSEI, t: "Today you learn the way of the <strong>trend</strong>. A trend is the direction the market is traveling — like a river's current." },
      { c: SENSEI, t: "An <strong>uptrend</strong> makes higher hills and higher valleys — climbing a mountain. ⛰️ A <strong>downtrend</strong> makes lower hills and lower valleys — sliding down. And sometimes the market moves <em>sideways</em>, just resting." },
      { c: KITSU,  t: "The ancient surfing wisdom, kya~: <strong>the trend is your friend!</strong> It is much easier to ride the wave 🌊 than to swim against it!" },
      { c: SENSEI, t: "This is why traders can profit in BOTH directions. Going <strong>LONG</strong> means you buy first, hoping the price rises. Going <strong>SHORT</strong> means you sell first, hoping the price falls — then you buy it back cheaper. With futures, both are normal moves!" },
      { c: KAZUO,  t: "Short selling blew my mind too. Think of it like this: you promise to deliver a card later, sell that promise for 12 Koins today, and when the card's price drops to 8, you grab one and deliver it. You keep the 4 Koin difference. Sneaky... but fair!" },
      { c: SENSEI, t: "Two more words of power: <strong>support</strong> is a floor where falling prices often bounce up. <strong>Resistance</strong> is a ceiling where rising prices often get rejected. Watch where the price bounced before — it remembers!" },
      { c: SENSEI, t: "Your mission in the dojo: watch the candles, find the wave's direction, and ride it. LONG in an uptrend, SHORT in a downtrend. Now prove your knowledge!" },
    ],
    quiz: [
      { q: "An uptrend looks like...",
        o: ["Lower hills and lower valleys", "Higher hills and higher valleys", "A flat line forever", "A circle"],
        a: 1, e: "Climbing the mountain! Each high is higher, each dip stops higher too." },
      { q: "Going SHORT means you profit when...",
        o: ["The price goes up", "The price goes down", "The market closes", "You hold for years"],
        a: 1, e: "Short = sell first, buy back cheaper later. Futures traders can ride waves down too!" },
      { q: "What is 'support'?",
        o: ["A floor where falling prices often bounce", "A ceiling that blocks prices", "A trading fee", "A type of candle"],
        a: 0, e: "Support is the floor 🛗 — prices often bounce up from it. Resistance is the ceiling." },
      { q: "Finish the surfer's wisdom: 'The trend is your...'",
        o: ["Enemy", "Homework", "Friend", "Sensei"],
        a: 2, e: "The trend is your friend! Riding the wave beats fighting it." },
      { q: "The market is in a strong downtrend. Which trade goes WITH the wave?",
        o: ["Going LONG", "Going SHORT", "Doing 100 trades", "Closing your eyes"],
        a: 1, e: "Downtrend → SHORT rides the wave down. LONG would be swimming against the current!" },
    ],
  },
  {
    id: "arc4",
    emoji: "🛡️",
    name: "Arc 4: The Way of the Shield",
    desc: "Risk management — the stop-loss is your legendary armor.",
    lessons: [
      { c: SENSEI, t: "Listen closely, for this is the <strong>most important arc of your entire training</strong>. Every anime hero needs armor. A trader's armor is called <em>risk management</em>." },
      { c: SENSEI, t: "Truth one: <strong>nobody wins every trade.</strong> Not me, not the greatest market samurai in history. Losing some trades is normal — like losing some battles in a long tournament arc." },
      { c: KITSU,  t: "So the real question isn't 'how do I never lose?' It's <strong>'how do I keep my losses SMALL?'</strong> Small scratches heal fast. Giant wounds end the adventure, kya~!" },
      { c: SENSEI, t: "Behold the legendary shield: the <strong>STOP-LOSS</strong>. 🛡️ When you open a trade, you set a line: 'If the price hits HERE, close my trade automatically.' It cuts a losing trade while the loss is still tiny." },
      { c: KAZUO,  t: "I learned this the hard way. Once I skipped my shield because I was SURE I was right. The market didn't care how sure I was. Now I never trade without a stop-loss. Never." },
      { c: SENSEI, t: "Rule of the dojo: <strong>risk only a small slice of your Koins on any one trade.</strong> Grown-up traders often risk just 1–2% per trade. Then even five losses in a row is just a training montage — not game over." },
      { c: SENSEI, t: "And beware the double-edged sword of futures: <strong>leverage</strong>. It makes wins bigger AND losses bigger. That is exactly why real futures are for trained adults only — and why the shield matters above all. Quiz, then the Shield Trial awaits in the dojo!" },
    ],
    quiz: [
      { q: "What does a stop-loss do?",
        o: ["Doubles your Koins", "Automatically closes your trade if the price hits your chosen line", "Stops the market", "Makes candles green"],
        a: 1, e: "It's your shield! It cuts a losing trade while the loss is still small." },
      { q: "Even legendary traders...",
        o: ["Win every single trade", "Never use stop-losses", "Lose some trades — and keep those losses small", "Trade without a plan"],
        a: 2, e: "Everyone loses sometimes. Champions just make sure the losses stay tiny." },
      { q: "How much of your Koins should you risk on ONE trade?",
        o: ["All of it — go big!", "Only a small slice", "Exactly half", "Borrow more to risk extra"],
        a: 1, e: "A small slice! Then a losing streak is just a training montage, not game over." },
      { q: "Leverage in futures trading...",
        o: ["Makes wins bigger and losses bigger", "Only makes wins bigger", "Removes all risk", "Is a kind of candy"],
        a: 0, e: "It's a double-edged sword ⚔️ — which is why real futures are for trained adults and why the shield is sacred." },
      { q: "Kazuo was SURE his trade would win, so he skipped his stop-loss. What does the market think about how sure he was?",
        o: ["The market rewards confidence", "The market doesn't care — always wear your shield", "The market felt sorry for him", "The market paused for him"],
        a: 1, e: "The market doesn't know or care what we believe. The shield goes on EVERY trade." },
    ],
  },
  {
    id: "arc5",
    emoji: "🧠",
    name: "Arc 5: Mind of the Trader",
    desc: "Defeat the inner demons: FOMO, revenge trading, and impatience.",
    lessons: [
      { c: SENSEI, t: "You have learned candles, waves, and the shield. But the final enemies are not on the chart. They live <strong>inside the trader's own mind</strong>. 👹" },
      { c: SENSEI, t: "Demon one: <strong>FOMO</strong> — the Fear Of Missing Out. The price rockets up, your heart screams <em>'JUMP IN NOW!'</em>... usually right before it falls back down. The patient ninja waits for the next proper setup." },
      { c: KAZUO,  t: "Demon two: <strong>Revenge Trading</strong>. You lose a trade, get angry, and instantly slam into another trade to 'win it back.' That's not a strategy — that's the demon driving. After a loss: breathe, review, reset." },
      { c: KITSU,  t: "Demon three: <strong>Overtrading</strong>, kya~! Trading every wiggle because sitting still feels boring. But a sniper takes few shots — the best traders spend most of the day just <em>watching</em>." },
      { c: SENSEI, t: "The weapon against all three demons is the <strong>trading plan</strong>. Before you trade, decide: <em>Why am I entering? Where is my shield? When will I take profit?</em> Then follow the plan like a sacred scroll." },
      { c: SENSEI, t: "And honor the <strong>trading journal</strong> 📓 — after each dojo day, ask: did I follow my plan? Heroes level up by reviewing their battles, not just fighting them." },
      { c: SENSEI, t: "Remember: a <em>good trade</em> is one where you followed your plan — even if it lost. A <em>bad trade</em> is breaking your rules — even if you got lucky and won. Discipline IS the superpower. Final quiz, then the boss awaits!" },
    ],
    quiz: [
      { q: "The price suddenly rockets up and you feel you MUST jump in right now. Which demon is whispering?",
        o: ["FOMO", "Support", "Leverage", "The trend"],
        a: 0, e: "That's FOMO — Fear Of Missing Out. The patient ninja waits for the next proper setup." },
      { q: "You just lost a trade. What does a disciplined trader do next?",
        o: ["Instantly open a bigger trade to win it back", "Breathe, review the plan, and reset", "Quit forever", "Remove the stop-loss next time"],
        a: 1, e: "Revenge trading is the demon driving. Breathe, review, reset." },
      { q: "What makes a trade a GOOD trade?",
        o: ["It made Koins, no matter how", "You followed your plan — win or lose", "It was exciting", "It was your 20th trade that day"],
        a: 1, e: "Discipline is the superpower. Following the plan is the win — profits follow over time." },
      { q: "What should you decide BEFORE entering a trade?",
        o: ["Nothing — wing it!", "Why you're entering, where your stop-loss is, and when you'll take profit", "Only how excited you feel", "What snack to eat"],
        a: 1, e: "That's the trading plan — your sacred scroll. 📜" },
      { q: "The best traders spend most of their day...",
        o: ["Trading every tiny wiggle", "Watching patiently and waiting for great setups", "Arguing online", "Asleep at the keyboard"],
        a: 1, e: "Like a sniper — few shots, carefully chosen. Overtrading drains your Koins!" },
    ],
  },
  {
    id: "arc6",
    emoji: "🐉",
    name: "Arc 6: The Final Trial",
    desc: "Face the Volatility Dragon and claim your legend.",
    lessons: [
      { c: SENSEI, t: "Young trader... you have come far. Candles, trends, the shield, the calm mind. One trial remains: the <strong>Volatility Dragon</strong>. 🐉" },
      { c: KITSU,  t: "Volatility means <strong>how wildly the price jumps around</strong>, kya~! Some days the market is a sleepy pond. Dragon days, it's a stormy ocean — huge candles, sudden reversals!" },
      { c: SENSEI, t: "On wild days, the wise trader adapts: <strong>trade smaller, keep the shield closer to your heart, and be pickier</strong> about which battles to fight. Wild markets give bigger chances — and bigger dangers." },
      { c: KAZUO,  t: "This is your graduation battle. Everything you've learned, all at once. Ride the waves, wear your shield, keep your mind calm even when the dragon roars. I'll be watching, rival. Don't lose." },
      { c: SENSEI, t: "Pass the final quiz, then enter the dojo for the <strong>Boss Battle</strong>. Survive the dragon's storm and finish the day with profit — and you shall be named a <strong>Legendary Trade Master</strong>. Go forth! ⚡" },
    ],
    quiz: [
      { q: "What is volatility?",
        o: ["How wildly the price jumps around", "The market's opening time", "A type of contract", "A trading fee"],
        a: 0, e: "Sleepy pond vs stormy ocean — volatility is the size of the waves." },
      { q: "On a wild, high-volatility day, the wise trader...",
        o: ["Risks everything for glory", "Trades smaller and is pickier about setups", "Removes all stop-losses", "Trades 100 times"],
        a: 1, e: "Bigger waves mean bigger danger — adapt by trading smaller with your shield up." },
      { q: "Which combo makes a complete trader?",
        o: ["Luck + speed", "Reading charts + risk management + a calm, disciplined mind", "Big bets + confidence", "Secrets + rumors"],
        a: 1, e: "All three pillars together — that's the way of the Trade Master. 🐉" },
      { q: "After this game, what's true about REAL futures trading?",
        o: ["It's easy free money", "Kids should try it with real money", "It's high-risk and only for trained adults", "It has no risk if you're smart"],
        a: 2, e: "Exactly. Real futures use leverage and real Koins... er, dollars. Train for years, study hard, and only adults with money they can afford to lose should ever try." },
    ],
  },
];

// ====== Dojo missions (unlock after finishing the named arc) ======
const MISSIONS = [
  {
    id: "m1", emoji: "👣", name: "First Steps", unlockArc: "arc2",
    goal: "Make your very first trade (long or short) and close it. Win or lose — just take the leap!",
    candles: 40, vol: 0.7, drift: 0.02,
    check: s => s.tradesClosed >= 1,
  },
  {
    id: "m2", emoji: "🌊", name: "Trend Rider", unlockArc: "arc3",
    goal: "Spot the wave and ride it: finish the day with POSITIVE Koins (P&L above 0).",
    candles: 48, vol: 0.7, drift: 0.12, trendy: true,
    check: s => s.tradesClosed >= 1 && s.pnl > 0,
  },
  {
    id: "m3", emoji: "🛡️", name: "Trial of the Shield", unlockArc: "arc4",
    goal: "Make at least 2 trades, EVERY trade protected by a stop-loss shield, and never let your day's loss pass 60 Koins.",
    candles: 48, vol: 0.9, drift: 0.0,
    check: s => s.tradesClosed >= 2 && s.allStopped && s.minPnl > -60,
  },
  {
    id: "m4", emoji: "🧘", name: "Calm Mind Challenge", unlockArc: "arc5",
    goal: "Patience, ninja: take 3 trades or FEWER the whole day and still finish with positive Koins.",
    candles: 56, vol: 0.8, drift: 0.08, trendy: true,
    check: s => s.tradesClosed >= 1 && s.tradesClosed <= 3 && s.pnl > 0,
  },
  {
    id: "m5", emoji: "🐉", name: "BOSS: Volatility Dragon", unlockArc: "arc6",
    goal: "Survive the dragon's storm! Finish the day positive, always use a stop-loss, and never drop below -100 Koins.",
    candles: 60, vol: 1.6, drift: 0.0, trendy: true, boss: true,
    check: s => s.pnl > 0 && s.allStopped && s.minPnl > -100,
  },
];

// ====== Badges ======
const BADGES = [
  { id: "first-trade",  emoji: "👣", name: "First Steps",     desc: "Closed your first trade" },
  { id: "shield",       emoji: "🛡️", name: "Shield Bearer",   desc: "A stop-loss saved you from a bigger loss" },
  { id: "green-day",    emoji: "🌞", name: "Green Day",       desc: "Finished a dojo day with profit" },
  { id: "quiz-ace",     emoji: "🎯", name: "Quiz Ace",        desc: "Perfect score on a quiz" },
  { id: "scholar",      emoji: "📚", name: "Dojo Scholar",    desc: "Finished all 6 story arcs" },
  { id: "patient",      emoji: "🧘", name: "Patient Ninja",   desc: "Won the Calm Mind Challenge" },
  { id: "dragon",       emoji: "🐉", name: "Dragon Slayer",   desc: "Defeated the Volatility Dragon" },
];

const XP_REWARDS = { lesson: 25, quizCorrect: 10, mission: 60, boss: 120 };
