// ====== Candle Quest Academy — story, lessons & quizzes ======
// Characters: Sensei Hoshi (wise owl mentor), Kitsu (fox mascot), Kazuo (friendly rival)

export const SENSEI = { name: "Sensei Hoshi", emoji: "🦉" };
const KITSU  = { name: "Kitsu the Fox", emoji: "🦊" };
const KAZUO  = { name: "Rival Kazuo", emoji: "😎" };

export const RANKS = [
  { xp: 0,   name: "Academy Rookie",        emoji: "🐣" },
  { xp: 80,  name: "Candle Cadet",          emoji: "🕯️" },
  { xp: 200, name: "Chart Ninja",           emoji: "🥷" },
  { xp: 350, name: "Risk Guardian",         emoji: "🛡️" },
  { xp: 520, name: "Market Samurai",        emoji: "⚔️" },
  { xp: 700, name: "Legendary Trade Master", emoji: "🐉" },
  { xp: 1050, name: "Mythic Chart Sage",     emoji: "🌌" },
  { xp: 1350, name: "Playbook Grandmaster",  emoji: "🍞" },
];

// Player hero avatars (Kai, Hana) live in js/characters.js as AVATARS.

// The two training beasts of the dojo. Prices are generated (no live feed),
// but each asset gets realistic levels and its own personality.
export const ASSETS = {
  NQ: {
    code: "NQ", emoji: "🚀", name: "Nasdaq-100 Futures",
    nickname: "the Lightning Stallion",
    desc: "Follows 100 giant tech companies. Fast and jumpy — big moves, big energy!",
    base: 21500, scale: 8, decimals: 0, volFactor: 1.1,
  },
  GC: {
    code: "GC", emoji: "🥇", name: "Gold Futures",
    nickname: "the Golden Dragon",
    desc: "The ancient treasure. Usually calmer — but it ROARS when the world gets scared.",
    base: 3350, scale: 2.4, decimals: 1, volFactor: 0.9,
  },
};

export const ARCS = [
  {
    id: "arc1",
    emoji: "⛩️",
    name: "Arc 1: Welcome to the Dojo",
    desc: "What is a market? What is a futures contract?",
    reflect: "In your own words: what is a futures contract, and why can a promise be worth something?",
    lessons: [
      { c: SENSEI, t: "Welcome, young trader! I am <strong>Sensei Hoshi</strong>, master of this dojo. You wish to learn the ancient art of <em>trading</em>? Then listen well!" },
      { c: SENSEI, t: "A <strong>market</strong> is simply a place where people <em>buy</em> and <em>sell</em> things. A school card-trading club is a market! Some kids want to buy a rare card, some want to sell one." },
      { c: KITSU,  scene: "market", t: "And here's the secret, kya~! Prices move because of <strong>buyers and sellers</strong>. If LOTS of kids want the rare dragon card, its price goes <em>UP</em>! If everyone wants to sell it... price goes <em>DOWN</em>!" },
      { c: SENSEI, t: "Now, the special scroll of this dojo: the <strong>futures contract</strong>. It is a <em>promise</em> to buy or sell something at a set price on a future day." },
      { c: SENSEI, scene: "dragonCard", t: "Imagine you tell your friend: <em>'Next Friday, I promise to trade you my dragon card for 10 Koins — no matter what!'</em> That promise itself becomes valuable. If the dragon card becomes super popular by Thursday, your friend's promise to get it for only 10 Koins is a treasure!" },
      { c: KAZUO,  t: "Heh. And real traders don't even wait until Friday. They buy and sell the <strong>promises themselves</strong>, all day long. Corn, gold, oil, stock indexes — there are futures for all of them." },
      { c: SENSEI, t: "In this dojo you will tame two legendary beasts. First: <strong>🚀 NQ — the Nasdaq-100 futures</strong>, the Lightning Stallion. It follows 100 giant tech companies and charges FAST — prices near <em>21,500</em>, leaping dozens of points in minutes!" },
      { c: KITSU,  t: "And second: <strong>🥇 GC — Gold futures</strong>, the Golden Dragon, kya~! The ancient treasure beast, trading near <em>3,350</em> an ounce. Usually calmer than NQ... but when the world gets scared, gold ROARS! Real traders watch exactly these two." },
      { c: SENSEI, t: "We will train as <strong>intraday traders</strong> — also called <em>day traders</em>. Our rule: every trade opens and closes on the <strong>same day</strong>. Like a ninja mission that must finish before sunset! 🌅" },
      { c: SENSEI, t: "One more thing, and it is the most important scroll of all: in this dojo we use pretend <strong>Koins</strong>. Real futures trading is <em>very risky</em> and only for trained adults. Master the art here first. Now — to your first quiz!" },
    ],
    quiz: [
      { q: "What is a market?",
        o: ["A place where people buy and sell things", "A type of video game", "A kind of candlestick", "A ninja weapon"],
        a: 0, e: "Yes! A market is anywhere buyers and sellers meet — even a card-trading club at school." },
      { q: "A futures contract is...",
        o: ["A magic spell", "A promise to buy or sell something at a set price on a future day", "A kind of money", "A chart pattern"],
        a: 1, e: "Exactly! It's a promise about a future trade — and traders trade the promises themselves." },
      { q: "If LOTS of people suddenly want to buy something, what usually happens to its price?",
        o: ["It goes down", "It disappears", "It goes up", "Nothing ever changes"],
        a: 2, e: "More buyers than sellers pushes the price UP. That's the heartbeat of every market!" },
      { q: "What is the day trader's golden rule in our dojo?",
        o: ["Hold trades for years", "Open and close every trade on the same day", "Only trade on weekends", "Never close a trade"],
        a: 1, e: "Right! Intraday means in-the-day. The mission ends before the market closes — like a ninja home before sunset." },
      { q: "Which two beasts will you train with in this dojo?",
        o: ["Corn and oil futures", "NQ (Nasdaq-100) and GC (Gold) futures", "Pokémon cards", "Bitcoin and bananas"],
        a: 1, e: "🚀 NQ the Lightning Stallion and 🥇 GC the Golden Dragon — a fast tech index and the ancient treasure!" },
    ],
  },
  {
    id: "arc2",
    emoji: "🕯️",
    name: "Arc 2: The Language of Candles",
    desc: "Read candlestick charts like a ninja reads scrolls.",
    reflect: "In your own words: what does a green candle tell you versus a red candle, and why are candles useful?",
    lessons: [
      { c: SENSEI, t: "To trade, you must read the market's secret language: the <strong>candlestick chart</strong>. Each candle tells the story of the price during a short time — like one panel in a manga!" },
      { c: SENSEI, t: "A candle has a thick <strong>body</strong> and thin <strong>wicks</strong> on top and bottom. The body shows where the price <em>opened</em> and where it <em>closed</em>." },
      { c: KITSU,  scene: "candles", t: "Color code, kya~! A <strong>green candle</strong> means the price went <em>UP</em> during that time — the heroes won that battle! A <strong>red candle</strong> means the price went <em>DOWN</em> — the bears won. 🐻" },
      { c: SENSEI, t: "The <strong>wicks</strong> are the shadows of the battle. The top wick shows the <em>highest</em> price reached; the bottom wick shows the <em>lowest</em>. A long wick means the price tried to go there... but got pushed back!" },
      { c: KAZUO,  t: "Pro tip: one candle is one panel, but the <strong>whole chart is the story</strong>. Lots of big green candles in a row? Buyers are powerful today. Lots of red? Sellers rule." },
      { c: SENSEI, t: "In our dojo's chart, each candle is a few minutes of the trading day. Watch them form, one by one, and you will feel the market's rhythm. Quiz time, then your <strong>first dojo mission</strong> awaits!" },
    ],
    quiz: [
      { q: "What does a GREEN candle mean?",
        o: ["The price went down", "The market is closed", "The price went up during that time", "A trade was cancelled"],
        a: 2, e: "Green = up! The price closed higher than it opened." },
      { q: "What do the thin wicks on a candle show?",
        o: ["The highest and lowest prices reached", "How many traders were online", "The candle's age", "Nothing important"],
        a: 0, e: "Wicks are the shadows of the battle — the extremes the price touched before getting pushed back." },
      { q: "You see many big RED candles in a row. Who is winning right now?",
        o: ["The buyers", "The sellers", "Nobody", "The referees"],
        a: 1, e: "Sellers (the bears 🐻) are in control — the price keeps closing lower." },
      { q: "The thick part of the candle is called the...",
        o: ["Wick", "Shadow", "Body", "Handle"],
        a: 2, e: "The body shows where price opened and closed. The wicks are the thin lines." },
    ],
  },
  {
    id: "arc3",
    emoji: "🌊",
    name: "Arc 3: Riding the Trend Wave",
    desc: "Trends, support & resistance — surf with the market, not against it.",
    reflect: "In your own words: why is it smarter to trade WITH the trend than against it?",
    lessons: [
      { c: SENSEI, t: "Today you learn the way of the <strong>trend</strong>. A trend is the direction the market is traveling — like a river's current." },
      { c: SENSEI, t: "An <strong>uptrend</strong> makes higher hills and higher valleys — climbing a mountain. ⛰️ A <strong>downtrend</strong> makes lower hills and lower valleys — sliding down. And sometimes the market moves <em>sideways</em>, just resting." },
      { c: KITSU,  scene: "trend", t: "The ancient surfing wisdom, kya~: <strong>the trend is your friend!</strong> It is much easier to ride the wave 🌊 than to swim against it!" },
      { c: SENSEI, scene: "longshort", t: "This is why traders can profit in BOTH directions. Going <strong>LONG</strong> means you buy first, hoping the price rises. Going <strong>SHORT</strong> means you sell first, hoping the price falls — then you buy it back cheaper. With futures, both are normal moves!" },
      { c: KAZUO,  t: "Short selling blew my mind too. Think of it like this: you promise to deliver a card later, sell that promise for 12 Koins today, and when the card's price drops to 8, you grab one and deliver it. You keep the 4 Koin difference. Sneaky... but fair!" },
      { c: SENSEI, t: "Two more words of power: <strong>support</strong> is a floor where falling prices often bounce up. <strong>Resistance</strong> is a ceiling where rising prices often get rejected. Watch where the price bounced before — it remembers!" },
      { c: SENSEI, t: "Your mission in the dojo: watch the candles, find the wave's direction, and ride it. LONG in an uptrend, SHORT in a downtrend. Now prove your knowledge!" },
    ],
    quiz: [
      { q: "An uptrend looks like...",
        o: ["Lower hills and lower valleys", "Higher hills and higher valleys", "A flat line forever", "A circle"],
        a: 1, e: "Climbing the mountain! Each high is higher, each dip stops higher too." },
      { q: "Going SHORT means you profit when...",
        o: ["The price goes up", "The price goes down", "The market closes", "You hold for years"],
        a: 1, e: "Short = sell first, buy back cheaper later. Futures traders can ride waves down too!" },
      { q: "What is 'support'?",
        o: ["A floor where falling prices often bounce", "A ceiling that blocks prices", "A trading fee", "A type of candle"],
        a: 0, e: "Support is the floor 🛗 — prices often bounce up from it. Resistance is the ceiling." },
      { q: "Finish the surfer's wisdom: 'The trend is your...'",
        o: ["Enemy", "Homework", "Friend", "Sensei"],
        a: 2, e: "The trend is your friend! Riding the wave beats fighting it." },
      { q: "The market is in a strong downtrend. Which trade goes WITH the wave?",
        o: ["Going LONG", "Going SHORT", "Doing 100 trades", "Closing your eyes"],
        a: 1, e: "Downtrend → SHORT rides the wave down. LONG would be swimming against the current!" },
    ],
  },
  {
    id: "arc4",
    emoji: "🛡️",
    name: "Arc 4: The Way of the Shield",
    desc: "Risk management — the stop-loss is your legendary armor.",
    reflect: "In your own words: why is a stop-loss so important? What could happen to your Koins without one?",
    lessons: [
      { c: SENSEI, t: "Listen closely, for this is the <strong>most important arc of your entire training</strong>. Every anime hero needs armor. A trader's armor is called <em>risk management</em>." },
      { c: SENSEI, t: "Truth one: <strong>nobody wins every trade.</strong> Not me, not the greatest market samurai in history. Losing some trades is normal — like losing some battles in a long tournament arc." },
      { c: KITSU,  t: "So the real question isn't 'how do I never lose?' It's <strong>'how do I keep my losses SMALL?'</strong> Small scratches heal fast. Giant wounds end the adventure, kya~!" },
      { c: SENSEI, scene: "shield", t: "Behold the legendary shield: the <strong>STOP-LOSS</strong>. 🛡️ When you open a trade, you set a line: 'If the price hits HERE, close my trade automatically.' It cuts a losing trade while the loss is still tiny." },
      { c: KAZUO,  t: "I learned this the hard way. Once I skipped my shield because I was SURE I was right. The market didn't care how sure I was. Now I never trade without a stop-loss. Never." },
      { c: SENSEI, t: "Rule of the dojo: <strong>risk only a small slice of your Koins on any one trade.</strong> Grown-up traders often risk just 1–2% per trade. Then even five losses in a row is just a training montage — not game over." },
      { c: SENSEI, t: "And beware the double-edged sword of futures: <strong>leverage</strong>. It makes wins bigger AND losses bigger. That is exactly why real futures are for trained adults only — and why the shield matters above all. Quiz, then the Shield Trial awaits in the dojo!" },
    ],
    quiz: [
      { q: "What does a stop-loss do?",
        o: ["Doubles your Koins", "Automatically closes your trade if the price hits your chosen line", "Stops the market", "Makes candles green"],
        a: 1, e: "It's your shield! It cuts a losing trade while the loss is still small." },
      { q: "Even legendary traders...",
        o: ["Win every single trade", "Never use stop-losses", "Lose some trades — and keep those losses small", "Trade without a plan"],
        a: 2, e: "Everyone loses sometimes. Champions just make sure the losses stay tiny." },
      { q: "How much of your Koins should you risk on ONE trade?",
        o: ["All of it — go big!", "Only a small slice", "Exactly half", "Borrow more to risk extra"],
        a: 1, e: "A small slice! Then a losing streak is just a training montage, not game over." },
      { q: "Leverage in futures trading...",
        o: ["Makes wins bigger and losses bigger", "Only makes wins bigger", "Removes all risk", "Is a kind of candy"],
        a: 0, e: "It's a double-edged sword ⚔️ — which is why real futures are for trained adults and why the shield is sacred." },
      { q: "Kazuo was SURE his trade would win, so he skipped his stop-loss. What does the market think about how sure he was?",
        o: ["The market rewards confidence", "The market doesn't care — always wear your shield", "The market felt sorry for him", "The market paused for him"],
        a: 1, e: "The market doesn't know or care what we believe. The shield goes on EVERY trade." },
    ],
  },
  {
    id: "arc5",
    emoji: "🧠",
    name: "Arc 5: Mind of the Trader",
    desc: "Defeat the inner demons: FOMO, revenge trading, and impatience.",
    reflect: "In your own words: what is FOMO, and how does a calm, patient trader beat it?",
    lessons: [
      { c: SENSEI, t: "You have learned candles, waves, and the shield. But the final enemies are not on the chart. They live <strong>inside the trader's own mind</strong>. 👹" },
      { c: SENSEI, scene: "fomo", t: "Demon one: <strong>FOMO</strong> — the Fear Of Missing Out. The price rockets up, your heart screams <em>'JUMP IN NOW!'</em>... usually right before it falls back down. The patient ninja waits for the next proper setup." },
      { c: KAZUO,  t: "Demon two: <strong>Revenge Trading</strong>. You lose a trade, get angry, and instantly slam into another trade to 'win it back.' That's not a strategy — that's the demon driving. After a loss: breathe, review, reset." },
      { c: KITSU,  t: "Demon three: <strong>Overtrading</strong>, kya~! Trading every wiggle because sitting still feels boring. But a sniper takes few shots — the best traders spend most of the day just <em>watching</em>." },
      { c: SENSEI, t: "The weapon against all three demons is the <strong>trading plan</strong>. Before you trade, decide: <em>Why am I entering? Where is my shield? When will I take profit?</em> Then follow the plan like a sacred scroll." },
      { c: SENSEI, t: "And honor the <strong>trading journal</strong> 📓 — after each dojo day, ask: did I follow my plan? Heroes level up by reviewing their battles, not just fighting them." },
      { c: SENSEI, t: "Remember: a <em>good trade</em> is one where you followed your plan — even if it lost. A <em>bad trade</em> is breaking your rules — even if you got lucky and won. Discipline IS the superpower. Final quiz, then the boss awaits!" },
    ],
    quiz: [
      { q: "The price suddenly rockets up and you feel you MUST jump in right now. Which demon is whispering?",
        o: ["FOMO", "Support", "Leverage", "The trend"],
        a: 0, e: "That's FOMO — Fear Of Missing Out. The patient ninja waits for the next proper setup." },
      { q: "You just lost a trade. What does a disciplined trader do next?",
        o: ["Instantly open a bigger trade to win it back", "Breathe, review the plan, and reset", "Quit forever", "Remove the stop-loss next time"],
        a: 1, e: "Revenge trading is the demon driving. Breathe, review, reset." },
      { q: "What makes a trade a GOOD trade?",
        o: ["It made Koins, no matter how", "You followed your plan — win or lose", "It was exciting", "It was your 20th trade that day"],
        a: 1, e: "Discipline is the superpower. Following the plan is the win — profits follow over time." },
      { q: "What should you decide BEFORE entering a trade?",
        o: ["Nothing — wing it!", "Why you're entering, where your stop-loss is, and when you'll take profit", "Only how excited you feel", "What snack to eat"],
        a: 1, e: "That's the trading plan — your sacred scroll. 📜" },
      { q: "The best traders spend most of their day...",
        o: ["Trading every tiny wiggle", "Watching patiently and waiting for great setups", "Arguing online", "Asleep at the keyboard"],
        a: 1, e: "Like a sniper — few shots, carefully chosen. Overtrading drains your Koins!" },
    ],
  },
  {
    id: "arc6",
    emoji: "🐉",
    name: "Arc 6: The Final Trial",
    desc: "Face the Volatility Dragon and claim your legend.",
    reflect: "In your own words: on a wild, high-volatility day, what should a trader do differently — and why?",
    lessons: [
      { c: SENSEI, t: "Young trader... you have come far. Candles, trends, the shield, the calm mind. One trial remains: the <strong>Volatility Dragon</strong>. 🐉" },
      { c: KITSU,  scene: "volatility", t: "Volatility means <strong>how wildly the price jumps around</strong>, kya~! Some days the market is a sleepy pond. Dragon days, it's a stormy ocean — huge candles, sudden reversals!" },
      { c: SENSEI, t: "On wild days, the wise trader adapts: <strong>trade smaller, keep the shield closer to your heart, and be pickier</strong> about which battles to fight. Wild markets give bigger chances — and bigger dangers." },
      { c: KAZUO,  t: "This is your graduation battle. Everything you've learned, all at once. Ride the waves, wear your shield, keep your mind calm even when the dragon roars. I'll be watching, rival. Don't lose." },
      { c: SENSEI, t: "Pass the final quiz, then enter the dojo for the <strong>Boss Battle</strong>. Survive the dragon's storm and finish the day with profit — and you shall be named a <strong>Legendary Trade Master</strong>. Go forth! ⚡" },
    ],
    quiz: [
      { q: "What is volatility?",
        o: ["How wildly the price jumps around", "The market's opening time", "A type of contract", "A trading fee"],
        a: 0, e: "Sleepy pond vs stormy ocean — volatility is the size of the waves." },
      { q: "On a wild, high-volatility day, the wise trader...",
        o: ["Risks everything for glory", "Trades smaller and is pickier about setups", "Removes all stop-losses", "Trades 100 times"],
        a: 1, e: "Bigger waves mean bigger danger — adapt by trading smaller with your shield up." },
      { q: "Which combo makes a complete trader?",
        o: ["Luck + speed", "Reading charts + risk management + a calm, disciplined mind", "Big bets + confidence", "Secrets + rumors"],
        a: 1, e: "All three pillars together — that's the way of the Trade Master. 🐉" },
      { q: "After this game, what's true about REAL futures trading?",
        o: ["It's easy free money", "Kids should try it with real money", "It's high-risk and only for trained adults", "It has no risk if you're smart"],
        a: 2, e: "Exactly. Real futures use leverage and real Koins... er, dollars. Train for years, study hard, and only adults with money they can afford to lose should ever try." },
    ],
  },
  {
    id: "arc7",
    emoji: "🚪",
    name: "Arc 7: The Way of Strategy",
    desc: "The Strategy Saga begins: price has a GOAL, fair value gaps (DEMs), walls — and the power of confluence.",
    reflect: "In your own words: why does price get 'pulled' to a fair value gap — and what is confluence?",
    lessons: [
      { c: SENSEI, t: "You thought your training ended with the dragon? Ha! True masters never stop learning. Welcome to the <strong>Strategy Saga</strong> — where feelings retire and <em>exact rules</em> take command." },
      { c: SENSEI, t: "A <strong>strategy</strong> is a set of rules decided BEFORE the battle: <em>when</em> to enter, <em>where</em> the shield goes, <em>when</em> to leave. Rules protect you from your own excited heart." },
      { c: SENSEI, t: "Rule scroll one: the <strong>Opening Range</strong>. Every morning the market fights its first battle. The first candles of the day draw the battlefield — the highest point is the <em>Range High</em>, the lowest is the <em>Range Low</em>." },
      { c: KITSU,  scene: "breakout", t: "And when the price SMASHES out of that range — that's the <strong>breakout</strong>, kya~! Bulls breaking the ceiling often keep charging UP. Bears breaking the floor often keep tumbling DOWN. Traders call this the <em>ORB</em> — Opening Range Breakout!" },
      { c: KAZUO,  t: "But watch for <strong>fake-outs</strong>: price pokes one toe out of the range, then dives right back in. I've been fooled plenty. That's exactly why one clue is never enough..." },
      { c: SENSEI, t: "Rule scroll two: the <strong>Gap</strong>. Sometimes price leaps so fast it skips a stair, leaving an empty zone on the chart — traders call it a <em>fair value gap</em>. Markets often come back to fill skipped stairs, and a fresh gap can act like a trampoline under a rising price." },
      { c: SENSEI, scene: "goal", t: "Now Dad's deepest secret. The market LOVES to be <strong>fair</strong> (balanced) — every price traded up and down evenly. A fast, one-sided move leaves an <em>unfair</em> empty gap. So the market feels <em>pulled</em> to come back and fill it. That's why <strong>price has a GOAL</strong> — it isn't wandering, it's being pulled to a magnet! 🧲" },
      { c: KITSU,  t: "That magnet is the fair value gap, kya~! Dad even has his own nickname for them: he calls them <strong>DEMs</strong>. So when you hear Dad say <em>'play it to that DEM'</em> — he just means that fair value gap! DEMs act like support and resistance, and price gets pulled toward them." },
      { c: KAZUO,  t: "When price reaches a goal, Dad watches <strong>bodies first, wicks second</strong>. He wants a candle <em>body</em> to close beyond the level to keep going. Two signals at a DEM: if price <em>pushes in</em> and pops back out, that's <strong>GAS</strong> ⛽ to continue. But if a candle <em>closes inside</em> it, price will likely keep filling the whole gap, step by step." },
      { c: SENSEI, t: "Rule scroll three: the <strong>Walls</strong>. The market remembers! <em>Yesterday's high and low</em> are walls in its memory. Breaking through a wall is a powerful sign — far stronger than wiggles in the middle of nowhere." },
      { c: SENSEI, t: "Now the secret that binds them: <strong>CONFLUENCE</strong>. One clue is a rumor. Two clues is a hint. <em>Three clues pointing the same way is a plan!</em> Breakout + Gap + Wall, all agreeing — that is when a strategist strikes." },
      { c: KITSU,  t: "In the dojo, your chart now shows all of it: the range zone, the gap boxes, the walls — and <strong>three signal lamps</strong> that light up as clues align. When all three glow the same direction... ⚡ kya~!" },
      { c: SENSEI, t: "Remember: a strategy does not win every battle — it wins the <em>war</em> by giving you an edge and keeping the demons out. Quiz time, then hunt the breakout!" },
    ],
    quiz: [
      { q: "What is the Opening Range?",
        o: ["The high and low drawn by the first candles of the day", "The market's lunch break", "A type of stop-loss", "Yesterday's price"],
        a: 0, e: "The morning's first battle draws the battlefield — its top is the Range High, its bottom the Range Low." },
      { q: "An ORB (Opening Range Breakout) trade means...",
        o: ["Trading randomly all morning", "Trading inside the range only", "Trading in the direction price breaks OUT of the opening range", "Never trading before lunch"],
        a: 2, e: "Breaking the ceiling → ride up. Breaking the floor → ride down. The breakout sets the direction." },
      { q: "What is a fair value gap?",
        o: ["A discount at the market shop", "An empty zone left when price leaps so fast it skips a stair", "A broken candle", "A kind of fee"],
        a: 1, e: "Skipped stairs! Markets often come back to fill them — and fresh gaps can act like trampolines." },
      { q: "Why does price get 'pulled' to a fair value gap?",
        o: ["Gaps are sticky", "The market wants to be FAIR, so it comes back to fill the unfair empty gap", "Gaps are heavy", "Traders push it there by hand"],
        a: 1, e: "A fast one-sided move leaves an unfair gap. The market feels pulled to fill it — that's why price has a goal! 🧲" },
      { q: "What does Dad call fair value gaps?",
        o: ["Holes", "DEMs", "Bricks", "Stairs"],
        a: 1, e: "DEMs! It's just Dad's nickname for a fair value gap. They act like support and resistance and pull price like magnets." },
      { q: "What should you do WHILE the opening range is still forming?",
        o: ["Trade as fast as possible", "Wait patiently — let the battlefield be drawn first", "Remove your stop-loss", "Close the game"],
        a: 1, e: "A strategist waits for the lines. No battlefield, no battle plan!" },
      { q: "What is confluence?",
        o: ["A trading fee", "When you feel really lucky", "Several independent clues all pointing the same direction", "A type of candle"],
        a: 2, e: "One clue is a rumor, three clues is a plan. Confluence = breakout + gap + wall agreeing!" },
    ],
  },
  {
    id: "arc8",
    emoji: "👺",
    name: "Arc 8: The Hype Demon",
    desc: "The most protective scroll: seeing through social media trading hype.",
    reflect: "In your own words: how can you tell a trading video online is hype, and why does one good day not prove a strategy?",
    lessons: [
      { c: SENSEI, t: "One final scroll, and it may protect you more than all the others combined. There is a demon that lives inside phones. I call it... the <strong>Hype Demon</strong>. 👺" },
      { c: KAZUO,  t: "I met it once. A video: <em>'My trading bot made 2,000 gold in THIRTY MINUTES!'</em> My heart raced. I almost sent the stranger my Koins to learn his secret. Then Sensei made me watch the video again... carefully." },
      { c: SENSEI, t: "Listen closely to such videos and you find the hidden truths: the same trader <strong>lost 2,000 gold three days earlier</strong>. His bot was broken for a week. It traded twice when it planned ten. Social media shows the <em>highlight reel</em> — never the report card." },
      { c: KITSU,  t: "The Hype Demon's favorite tricks, kya~! 🚩 Promises of easy money. 🚩 Only wins shown, never losses. 🚩 Big numbers + short time. 🚩 'Secret strategy' for sale. 🚩 'Almost funded, trust me!' Spot one flag, look for the rest!" },
      { c: SENSEI, t: "Now the deepest wisdom: <strong>sample size</strong>. Flip a coin three times and get three heads — is the coin magic? Of course not! One green day proves NOTHING. A real strategy is judged over <em>many, many trades</em> — like a season, not one match." },
      { c: SENSEI, t: "So what does a wise trader do with a shiny new strategy? <strong>Test before trust.</strong> Try it with pretend Koins, many times, write down every result — wins AND losses — and judge the whole table. That is called being a <em>scientist</em>. 🔬" },
      { c: SENSEI, t: "Your final mission awaits: the <strong>Strategy Scientist</strong> trial — five trading days, one strategy, honest results. You pass by <em>following the method</em>, not by getting lucky. Win or lose, the scientist always learns. Now, the quiz!" },
    ],
    quiz: [
      { q: "A video says: 'My bot made 2,000 gold in 30 minutes!' What's the FIRST question a wise trader asks?",
        o: ["Where do I send my Koins?", "What about all the losing days they didn't show?", "How do I make my own video?", "Is gold tasty?"],
        a: 1, e: "The highlight reel hides the report card. The same trader in our story lost 2,000 just days before!" },
      { q: "Which of these is a Hype Demon red flag?",
        o: ["Showing both wins AND losses honestly", "Promising easy money fast", "Explaining the risks", "Keeping a careful journal"],
        a: 1, e: "Easy money promises are the demon's favorite perfume. Real trading is slow, careful work." },
      { q: "A strategy wins 3 trades in a row. What does that prove?",
        o: ["It's unbeatable — bet everything!", "Almost nothing — 3 is a tiny sample", "The trader is a wizard", "The market is broken"],
        a: 1, e: "Three coin flips landing heads doesn't make a magic coin. Judge strategies over MANY trades." },
      { q: "You find an exciting new strategy on the internet. What do you do?",
        o: ["Use real money immediately", "Test it with pretend Koins many times and record ALL results", "Share it before checking it", "Assume it works because the video was cool"],
        a: 1, e: "Test before trust! The dojo (and paper trading) exists exactly for this." },
      { q: "In the Strategy Scientist mission, how do you PASS?",
        o: ["By getting lucky on day one", "By making the biggest possible profit", "By following the method honestly all five days — win or lose", "By trading without a shield"],
        a: 2, e: "Scientists are judged by their method, not one lucky result. Follow the rules, record the truth!" },
    ],
  },
  {
    id: "arc9",
    emoji: "💧",
    name: "Arc 9: The Liquidity Map",
    desc: "PDH, PDL, PDO, PDC, PD 50% — find the treasure pools where the orders sleep.",
    reflect: "In your own words: what is a liquidity sweep, and why shouldn't you chase price into the pool?",
    lessons: [
      { c: SENSEI, t: "One final secret map, young sage. <strong>Liquidity</strong> means how many orders are <em>waiting</em> to trade at each price. Some prices are quiet ponds... others are deep <strong>treasure pools</strong> full of resting orders. 💧" },
      { c: SENSEI, t: "Pools form at the famous levels every trader watches — especially <strong>yesterday's battle marks</strong>: <em>PDH</em> (Previous Day High), <em>PDL</em> (Previous Day Low), <em>PDO</em> (Previous Day Open), and <em>PDC</em> (Previous Day Close)." },
      { c: KITSU,  t: "And don't forget the middle of yesterday's range — <strong>PD 50%</strong>, the <em>equilibrium</em>, kya~! Above it, buyers feel strong. Below it, sellers rule. Five magic lines you can draw <em>before the day even begins</em>!" },
      { c: KAZUO,  scene: "sweep", t: "Now the sneaky part. Just ABOVE the PDH rest piles of stop orders — other traders' shields. When price spikes up there, those orders get gobbled... and SNAP, price often reverses! Traders call it a <strong>liquidity sweep</strong> — the stop hunt." },
      { c: SENSEI, t: "So the wise trader never <em>chases</em> price into a pool. Watch the <strong>reaction</strong> instead: a sweep followed by a snap-back tells you the pool is empty — the move may be done, and the snap-back may be the real trade." },
      { c: SENSEI, t: "This is also the deep truth of <strong>support and resistance</strong>: support is a floor of waiting buyers; resistance is a ceiling of waiting sellers. And the great secret — when a ceiling truly breaks, it often <em>becomes</em> a floor. The <strong>role flip</strong>!" },
      { c: KITSU,  t: "In the dojo's <strong>Liquidity Hunter</strong> mission, all five lines are drawn for you, with the pools 💧 glowing beyond PDH and PDL. When a sweep happens, the log shouts and the chart shakes, kya~!" },
      { c: SENSEI, t: "Remember the creed: <em>levels are magnets and walls, sweeps are traps for the impatient, and reactions are the truth.</em> Take the quiz — then go fish where the fish are! 🎣" },
    ],
    quiz: [
      { q: "What is liquidity?",
        o: ["How fast the internet is", "How many orders are waiting to trade at each price", "A type of candle", "The market's opening time"],
        a: 1, e: "Quiet ponds vs deep treasure pools — liquidity is the resting orders at each level." },
      { q: "What does PDH stand for?",
        o: ["Previous Day High", "Pretty Big Hill", "Price Drop Hour", "Previous Dragon Hoard"],
        a: 0, e: "PDH = Previous Day High. Its siblings: PDL (low), PDO (open), PDC (close), PD 50% (the middle)." },
      { q: "Where do big clusters of stop orders usually rest?",
        o: ["Exactly at PD 50%", "Just above PDH and just below PDL", "Nowhere — stops are random", "Only at round numbers"],
        a: 1, e: "Shields gather just beyond yesterday's extremes — that's why those pools attract price!" },
      { q: "What is a liquidity sweep?",
        o: ["Cleaning the trading desk", "Price poking past a famous level to grab orders, then snapping back", "A type of broom", "Holding a trade for a week"],
        a: 1, e: "The stop hunt! Price raids the pool, gobbles the orders, and often reverses." },
      { q: "A strong ceiling (resistance) finally breaks. What does it often become?",
        o: ["Nothing", "A new floor (support) — the role flip", "A bigger ceiling", "A fair value gap"],
        a: 1, e: "The role flip — old resistance becomes new support. The market remembers its battles!" },
      { q: "What is PD 50%?",
        o: ["Half of your Koins", "The middle of yesterday's range — the equilibrium", "A 50% discount", "Half a candle"],
        a: 1, e: "The equilibrium line: above it buyers feel strong, below it sellers rule." },
    ],
  },
  {
    id: "arc10",
    emoji: "🍞",
    name: "Arc 10: The B.R.E.A.D Playbook (Dad's Method)",
    desc: "Dad's real recipe: Behavior, Respect, Execution, Alignment, Discipline — only mark levels price actually respects.",
    reflect: "In your own words: how do you tell a RESPECTED level from a DISRESPECTED one — and why should you only mark the respected ones?",
    lessons: [
      { c: SENSEI, t: "Young trader… you have learned every ingredient. Now I hand you <em>your father's own recipe</em> — the checklist he runs every single time. We call it the <strong>B.R.E.A.D playbook</strong>: <em>Behavior, Respect, Execution, Alignment, Discipline</em>. This is exactly how Dad trades. 🍞" },
      { c: SENSEI, t: "<strong>B — Behavior.</strong> Dad's first law: <strong>the higher timeframe is KING.</strong> 👑 Price cares about the big map — the 4-hour and 1-hour — not the noise on the tiny charts. Read the big picture FIRST and ask: <em>what is price being pulled toward?</em> A high, a low, or a gap. That magnet is your <strong>goal</strong>." },
      { c: KITSU,  t: "And here's Dad's habit, kya~! <strong>Every new hour, go look again.</strong> ⏰ A fresh 1-hour candle opens? Check if your story still holds. You might wake up bullish and the new hour flips bearish. Re-check the 4h, the 1h, then your little chart — every hour, no being lazy!" },
      { c: KAZUO,  scene: "respected", t: "<strong>R — Respect.</strong> This is Dad's BIGGEST secret, so listen close. Not every level matters! A level is only <strong>RESPECTED</strong> if, when it formed, price did <em>two things</em>: ① made a <strong>fair value gap</strong> (a gap-of-gas) in that direction, AND ② closed a <strong>body</strong> BEYOND the last swing high (going up) or last swing low (going down) before the pullback. That's price <em>proving</em> buyers or sellers were truly there." },
      { c: KAZUO,  t: "If a level did NOT do something new — if price <em>failed</em> to close a body beyond that last swing — then it is <strong>DISRESPECTED</strong>. ❌ When price comes back, it runs <em>straight through</em> like the line was never there. So Dad's rule: <em>stop marking disrespected levels!</em> Only draw the ones price actually respects — those are the magnets price gets pulled to." },
      { c: KITSU,  t: "Here's the whole GAME in one move, kya~! With your respected levels drawn, you just play <strong>zone to zone</strong>. When price reaches a level, watch the candle <em>close</em>: if it <strong>rejects</strong> (bounces off), price swings back toward the <em>last</em> zone. If it <strong>closes BEYOND</strong> the level, that zone is beaten — price heads to the <em>NEXT</em> zone. Bounce = back, break = onward. That's it! 🎯" },
      { c: KAZUO,  scene: "gap", t: "One more thing Dad showed: sometimes the market <strong>GAPS</strong> — a big jump up or down while you slept. Two rules. ① A gap does <em>NOT</em> make your zone more likely to hit — don't get excited. ② Treat it as a <strong>break-and-retest</strong>: price usually dips back to fill the gap, uses it as <strong>gas</strong> ⛽, then continues. Mark it from the <em>body</em> of the last candle before the jump." },
      { c: SENSEI, scene: "bread", t: "<strong>E — Execution.</strong> Dad only takes trades at the <strong>highs and lows</strong> of his 4h/1h levels — or a clean <em>retest</em> of them. <strong>NEVER the middle.</strong> 🚫 And his favorite entry: price <em>sweeps</em> a high or low, gets a little gas, then <strong>fails to do something new</strong> — it can't close beyond. THAT'S the trap. He plays it back the other way." },
      { c: SENSEI, t: "Dad says: <em>forget the first move — get the SECOND one.</em> Wait until price shows you, <strong>'we've been here before,'</strong> then let it prove your idea is right. And never chase! Price will <em>always</em> come back for you before the big move. Patience over FOMO, every time. 🧘" },
      { c: KAZUO,  t: "One more iron rule: Dad only takes <strong>bounces and rejects</strong> off his levels — <em>never continuations.</em> If he's not already in the trade, he does NOT chase price running through the middle. He waits for price to come back to a level and react. Bounce or reject — that's the only invitation." },
      { c: KAZUO,  t: "<strong>A — Alignment.</strong> Two timeframes, minimum — a higher and a lower — and they must <em>agree</em>. That's <strong>confluence</strong>. The 2-minute might scream 'go!' but if the 15-minute and the hour say no, you do NOT have alignment. And Dad's law: <strong>only trade in the direction of the higher timeframe.</strong> Read what price is actually saying — not what you <em>want</em> it to say." },
      { c: KAZUO,  t: "Your <strong>stop-loss</strong> goes where price <em>shouldn't have to return</em> — beyond the structure you traded off. If you swept a low and turned up, price shouldn't come back below that low. Get in, let price get <em>away</em> from your entry, then slide your stop to a safe spot. Protect the Koins first; never let a winner stop you out at a loss." },
      { c: SENSEI, t: "<strong>D — Discipline.</strong> Dad's 2026 rules, straight from his playbook: <strong>① Max 3 trades a session</strong> — then DONE, no matter the profit. <strong>② No alert, no trade</strong> — set alerts, walk away, only return when price reaches your zone. <strong>③ No inside days</strong> stuck between two 'gas stations.' <strong>④ Only the higher-timeframe direction.</strong> Less screen time, more patience. Take the quiz, then run Dad's checklist in the dojo!" },
    ],
    quiz: [
      { q: "What makes a level RESPECTED (worth marking)?",
        o: ["Any level price touched once", "When it formed, price made a fair value gap AND closed a body beyond the last swing high/low", "A level with a round number", "The very first level of the day"],
        a: 1, e: "Two proofs: a fair value gap in that direction AND a body close beyond the last swing. That's price proving buyers/sellers were really there." },
      { q: "What happens when price returns to a DISRESPECTED level?",
        o: ["It bounces hard", "It usually runs straight through it", "It always reverses", "It stops and waits a day"],
        a: 1, e: "Disrespected levels failed to do something new — so price blasts through them. That's why Dad says stop marking them!" },
      { q: "Playing 'zone to zone': price REJECTS (bounces off) a level. Where does it go?",
        o: ["Straight to the next zone", "Back toward the previous zone", "Nowhere — it stops", "It always crashes"],
        a: 1, e: "Bounce = back to the last zone. If instead it CLOSES BEYOND the level, that zone is beaten and price heads to the next one." },
      { q: "The market opens with a big GAP up. What's true?",
        o: ["A gap guarantees price reaches your zone", "A gap doesn't boost the odds — treat it as a break-and-retest and let price use it as gas", "You should never trade again that day", "A gap means trade the middle"],
        a: 1, e: "Gaps don't increase probability. Treat them as a break-retest: price fills the gap, uses it as gas ⛽, then continues." },
      { q: "In Behavior, which timeframe is KING?",
        o: ["The 30-second chart", "The 1-minute chart", "The higher timeframe (4-hour / 1-hour)", "Whatever feels right"],
        a: 2, e: "Higher timeframe is king. Price cares about the big map, not the noise — and you re-check it every new hour." },
      { q: "Dad's favorite entry is a sweep that does WHAT?",
        o: ["Closes far beyond the level (something new)", "Sweeps the high/low, then FAILS to do something new — so you play it back", "Trades the exact middle of the range", "Chases the first big move"],
        a: 1, e: "Sweep → fail to do something new → reverse. Forget the first move, get the second one: 'we've been here before.'" },
      { q: "Where does Dad take entries?",
        o: ["Anywhere in the middle of the range", "Only at the 4h/1h highs and lows, or a retest of them", "Only at lunchtime", "Wherever the 30-second chart says"],
        a: 1, e: "Highs and lows only — never the middle. The middle is low-probability; the edges are where the real reactions happen." },
      { q: "Which is one of Dad's 2026 Discipline rules?",
        o: ["Trade as many times as you want", "Trade even with no alert", "Max 3 trades a session, then you're done", "Always trade inside days"],
        a: 2, e: "Max 3 trades, no alert = no trade, no inside days between two gas stations, and only the higher-timeframe direction. Discipline first!" },
    ],
  },
];

// ====== Dojo missions (unlock after finishing the named arc) ======
export const MISSIONS = [
  {
    id: "m1", emoji: "👣", name: "First Steps", unlockArc: "arc2",
    goal: "Make your very first trade (long or short) and close it. Win or lose — just take the leap!",
    candles: 40, vol: 0.7, drift: 0.02,
    check: s => s.tradesClosed >= 1,
  },
  {
    id: "m2", emoji: "🌊", name: "Trend Rider", unlockArc: "arc3",
    goal: "Spot the wave and ride it: finish the day with POSITIVE Koins (P&L above 0).",
    candles: 48, vol: 0.7, drift: 0.12, trendy: true,
    check: s => s.tradesClosed >= 1 && s.pnl > 0,
  },
  {
    id: "m3", emoji: "🛡️", name: "Trial of the Shield", unlockArc: "arc4",
    goal: "Make at least 2 trades, EVERY trade protected by a stop-loss shield, and never let your day's loss pass 60 Koins.",
    candles: 48, vol: 0.9, drift: 0.0,
    check: s => s.tradesClosed >= 2 && s.allStopped && s.minPnl > -60,
  },
  {
    id: "m4", emoji: "🧘", name: "Calm Mind Challenge", unlockArc: "arc5",
    goal: "Patience, ninja: take 3 trades or FEWER the whole day and still finish with positive Koins.",
    candles: 56, vol: 0.8, drift: 0.08, trendy: true,
    check: s => s.tradesClosed >= 1 && s.tradesClosed <= 3 && s.pnl > 0,
  },
  {
    id: "m5", emoji: "🐉", name: "BOSS: Volatility Dragon", unlockArc: "arc6",
    goal: "Survive the dragon's storm! Finish the day positive, always use a stop-loss, and never drop below -100 Koins.",
    candles: 60, vol: 1.6, drift: 0.0, trendy: true, boss: true,
    check: s => s.pnl > 0 && s.allStopped && s.minPnl > -100,
  },
  {
    id: "m6", emoji: "🚪", name: "ORB Hunter", unlockArc: "arc7",
    goal: "The strategy chart is ON! Wait for the opening range to finish, trade ONLY in the breakout direction, and end the day positive.",
    candles: 48, vol: 0.8, drift: 0.12, trendy: true, strategy: true, orLen: 8,
    check: s => s.tradesClosed >= 1 && s.rangeTrades === 0 && s.allBreakoutAligned && s.pnl > 0,
  },
  {
    id: "m7", emoji: "🪜", name: "Gap Filler", unlockArc: "arc7",
    goal: "Enter at least one trade while a fresh gap supports your direction (watch the 🪜 lamp!), and finish the day positive.",
    candles: 48, vol: 1.0, drift: 0.1, trendy: true, strategy: true, orLen: 8,
    check: s => s.fvgAlignedTrades >= 1 && s.pnl > 0,
  },
  {
    id: "m8", emoji: "🔬", name: "Strategy Scientist", unlockArc: "arc8",
    goal: "The 5-day experiment! Trade the ORB strategy for five short days: never trade during the range, only breakouts, always shielded, 3+ trades total. You pass by FOLLOWING THE METHOD — profit doesn't matter, honesty does!",
    candles: 30, vol: 0.8, drift: 0.12, trendy: true, strategy: true, orLen: 6, days: 5,
    check: s => s.tradesClosed >= 3 && s.rangeTrades === 0 && s.allBreakoutAligned && s.allStopped,
  },
  {
    id: "m9", emoji: "💧", name: "Liquidity Hunter", unlockArc: "arc9",
    goal: "All five level lines are drawn (PDH, PDL, PDO, PDC, PD 50%). Wait for a liquidity SWEEP of PDH or PDL, trade the snap-back direction within 10 candles, keep every trade shielded, and finish positive!",
    candles: 52, vol: 1.0, drift: 0.08, trendy: true, liquidity: true,
    check: s => s.sweepTrades >= 1 && s.allStopped && s.pnl > 0,
  },
  {
    id: "m10", emoji: "🍞", name: "B.R.E.A.D Discipline", unlockArc: "arc10",
    goal: "Run Dad's checklist! Wait for full ⚡ CONFLUENCE (all 3 signal lamps agree), enter ONLY then, keep every trade shielded, stay patient (3 trades or fewer), and finish the day positive.",
    candles: 80, vol: 0.8, drift: 0.2, trendy: true, strategy: true, orLen: 8,
    check: s => s.confluenceTrades >= 1 && s.allStopped && s.tradesClosed >= 1 && s.tradesClosed <= 3 && s.pnl > 0,
  },
];

// ====== Badges ======
export const BADGES = [
  { id: "first-trade",  emoji: "👣", name: "First Steps",     desc: "Closed your first trade" },
  { id: "shield",       emoji: "🛡️", name: "Shield Bearer",   desc: "A stop-loss saved you from a bigger loss" },
  { id: "green-day",    emoji: "🌞", name: "Green Day",       desc: "Finished a dojo day with profit" },
  { id: "quiz-ace",     emoji: "🎯", name: "Quiz Ace",        desc: "Perfect score on a quiz" },
  { id: "scholar",      emoji: "📚", name: "Dojo Scholar",    desc: "Finished every story arc" },
  { id: "patient",      emoji: "🧘", name: "Patient Ninja",   desc: "Won the Calm Mind Challenge" },
  { id: "dragon",       emoji: "🐉", name: "Dragon Slayer",   desc: "Defeated the Volatility Dragon" },
  { id: "strategist",   emoji: "📐", name: "Strategist",      desc: "Cleared ORB Hunter by the rules" },
  { id: "scientist",    emoji: "🔬", name: "True Scientist",  desc: "Completed the 5-day strategy experiment" },
  { id: "hype-slayer",  emoji: "🚩", name: "Hype Slayer",     desc: "Saw through every Hype Demon trick (perfect Arc 8 quiz)" },
  { id: "pool-hunter",  emoji: "💧", name: "Pool Hunter",     desc: "Traded a liquidity sweep like a pro" },
  { id: "playbook",     emoji: "🍞", name: "Playbook Trader", desc: "Cleared the B.R.E.A.D Discipline mission by the checklist" },
];

export const XP_REWARDS = { lesson: 25, quizCorrect: 10, mission: 60, boss: 120 };
